---
- hosts: TestVM2
  remote_user: cc
  become: yes
  collections:
    - openstack.cloud

  tasks:
  - name: config kafka with zookeeper - VM2
    copy:
      src: vm2_kafka_zookeepter/server.properties
      dest: /home/cc/kafka_2.13-2.4.0/config
...
