---
- hosts: TestVM2 #create topics on VM2
  remote_user: cc
  become: true
  gather_facts: no
  collections:
    - openstack.cloud

  tasks:
  - name: create topics (topic1 topic2) on VM2
    shell: |
      cd /home/cc/kafka_2.13-2.4.0
      bin/kafka-topics.sh --create --topic topic1 --bootstrap-server 129.114.25.91:9092
      bin/kafka-topics.sh --create --topic topic2 --bootstrap-server 129.114.25.91:9092
...
